### ISSUE TITLE
New Warnings Broke

### ISSUE THREAD

**Issue by shackrat** [raingggg/coctohug#14]
The "New Warnings" pane does nothing.  Three remote harvester process on two harvester servers crashed overnight.  There was nothing to indicate in the New Warnings page that there was a loss of connectivity.  There was nothing to indicate the drop in plots.

I attempted to use Discord chat but the user rainggg was argumentative and rude, and would not own up to the massive number of bugs in this software.

Seems like this is scam software to get peoples keys.  I would avoid at all costs.

**Comment by raingggg** [comment]
coctohug builds docker from official fork source code: https://github.com/raingggg/coctohug/tree/main/dockers
Please kindly log fork related issue to each fork. You may also find the official fork github dockers folder.
